### ISSUE TITLE
不知道为什么直接访问 blog 是乱码

### ISSUE THREAD

**Issue by Tedko** [Tsien/tsien.github.com#1]
我尝试了 utf8，utf16，gb 等等。

**Comment by Tsien** [comment]
你好，请问你是什么浏览器、系统？
blog: tsien.github.io

**Comment by Tedko** [comment]
osx 10.11 chrome

**Comment by Tedko** [comment]
<img width="1280" alt="2016-01-16 2 38 52" src="https://cloud.githubusercontent.com/assets/6687437/12374861/fde4f066-bc5e-11e5-82e5-1ae3ee0f55ef.png">

**Comment by Tsien** [comment]
我修改了设置，你再试一下行不行。如果不行，我暂时也不知道怎么解决。
网上查了一些资料，应该是因为jekyll对中文的支持出问题了。但因为我这里显示都正常，不太方便调试。
多谢你的反馈！

**Comment by Tedko** [comment]
手机上看正常了（ios safari）明天我试试看电脑

**Comment by Tedko** [comment]
Safari on Mac 没问题。 Chrome 还是有问题。你试试看 chrome？

Suji YHWH <yanhan02008@gmail.com>于2016年1月17日周日 上午3:05写道：

> 手机上看正常了（ios safari）明天我试试看电脑
>

**Comment by Tsien** [comment]
我chrome、safari都显示正常＝＝
Chrome Version 47.0.2526.111 (64-bit)
OSX EI Capitan Version 10.11.2 (英文版)

**Comment by Tedko** [comment]
我确认了下编码没有问题，因为我复制出来的 blog 内容在别的地方可以正常显示。好谜……
Fc Tsien <notifications@github.com>于2016年1月17日周日 下午9:22写道：
